"""Regenerate the frontend's bundled copy of the pipeline catalogue.

The backend is the source of truth. The frontend bundles a copy so the
walkthrough's written content still renders with the API stopped; this script
keeps the two from drifting.

    python scripts/sync_frontend_catalogue.py
"""

from __future__ import annotations

import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

from app.data.pipeline_steps import PIPELINE_STAGES  # noqa: E402

HEADER = """/**
 * Bundled copy of the 16-step catalogue.
 *
 * The backend is the source of truth; the demo fetches from it on load. This
 * copy exists so the walkthrough's written content still renders with the API
 * offline. It carries no outputs - a step that has not been implemented has no
 * numbers to report.
 *
 * GENERATED by backend/scripts/sync_frontend_catalogue.py - do not edit by hand.
 */

import type { PipelineStage } from '@/types/pipeline'

export const BUNDLED_STAGES: PipelineStage[] = """

TARGET = (
    pathlib.Path(__file__).resolve().parents[2]
    / "frontend"
    / "src"
    / "features"
    / "pipeline"
    / "data"
    / "stages.ts"
)


def main() -> None:
    items = [stage.model_dump(by_alias=True, mode="json") for stage in PIPELINE_STAGES]
    body = json.dumps(items, indent=2, ensure_ascii=False)
    TARGET.write_text(HEADER + body + "\n", encoding="utf-8")
    print(f"wrote {TARGET} ({len(items)} stages)")


if __name__ == "__main__":
    main()
